// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var TestUtils = require("./TestUtils.bs.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ReactTestingLibrary = require("bs-react-testing-library/src/ReactTestingLibrary.bs.js");
var Listboxkit__Dropdown = require("../Listboxkit__Dropdown.bs.js");

var options = [
  "Red",
  "Green",
  "Blue"
];

function DropdownTest$DropdownListboxComponent(Props) {
  var multiSelectOpt = Props.multiSelect;
  var multiSelect = multiSelectOpt !== undefined ? multiSelectOpt : false;
  var match = Listboxkit__Dropdown.useDropdownListbox(options, multiSelect, undefined);
  var getOptionProps = match.getOptionProps;
  var highlightedIndex = match.highlightedIndex;
  var match$1 = Curry._1(match.getContainerProps, undefined);
  var onKeyDown = match$1.onKeyDown;
  var dropdownProps = Curry._1(match.getDropdownProps, undefined);
  var selectedOption = $$String.trim(Belt_Array.joinWith(Belt_Array.map(match.selectedIndexes, (function (index) {
                  return Belt_Array.get(options, index);
                })), ", ", (function (s) {
              return s;
            })));
  return React.createElement("div", undefined, React.createElement("div", {
                  role: dropdownProps.role,
                  tabIndex: dropdownProps.tabIndex,
                  onKeyDown: dropdownProps.onKeyDown,
                  onClick: dropdownProps.onClick
                }, selectedOption, React.createElement("div", {
                      hidden: !match.menuVisible,
                      role: match$1.role,
                      tabIndex: match$1.tabIndex,
                      onKeyDown: onKeyDown,
                      onFocus: match$1.onFocus,
                      onBlur: match$1.onBlur
                    }, $$Array.mapi((function (index, option) {
                            var match = Curry._1(getOptionProps, index);
                            var highlighted = highlightedIndex === index;
                            return React.createElement("div", {
                                        key: option,
                                        "aria-selected": match["aria-selected"],
                                        role: match.role,
                                        onKeyDown: onKeyDown,
                                        onClick: match.onClick
                                      }, highlighted ? "* " + option : option);
                          }), options))));
}

var DropdownListboxComponent = {
  options: options,
  make: DropdownTest$DropdownListboxComponent
};

function component(multiSelectOpt, param) {
  var multiSelect = multiSelectOpt !== undefined ? multiSelectOpt : false;
  return React.createElement(DropdownTest$DropdownListboxComponent, {
              multiSelect: multiSelect
            });
}

Jest.test("select option when clicked", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        var arg = TestUtils.FireEvent.click;
        var partial_arg = {
          NAME: "Str",
          VAL: "button"
        };
        var arg$1 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg, param, param$1);
        };
        Curry._2(arg, undefined, Curry._2(arg$1, undefined, component$1));
        var partial_arg$1 = {
          NAME: "Str",
          VAL: "listbox"
        };
        var arg$2 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$1, param, param$1);
        };
        TestUtils.assertAndContinue(TestUtils.toBeVisible(expect(Curry._2(arg$2, undefined, component$1))));
        var arg$3 = TestUtils.FireEvent.click;
        Curry._2(arg$3, undefined, ReactTestingLibrary.getByRole({
                  NAME: "Str",
                  VAL: "option"
                }, {
                  name: "Blue"
                }, component$1));
        var partial_arg$2 = {
          NAME: "Str",
          VAL: "Blue"
        };
        var arg$4 = function (param) {
          return TestUtils.toHaveTextContent(partial_arg$2, param);
        };
        var partial_arg$3 = {
          NAME: "Str",
          VAL: "button"
        };
        var arg$5 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$3, param, param$1);
        };
        return Curry._2(arg$4, undefined, expect(Curry._2(arg$5, undefined, component$1)));
      }));

Jest.test("show listbox when pressing arrow down", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        var partial_arg = {
          NAME: "Str",
          VAL: "button"
        };
        var arg = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg, param, param$1);
        };
        Curry._1(TestUtils.FireEvent.pressDown, Curry._2(arg, undefined, component$1));
        var partial_arg$1 = {
          NAME: "Str",
          VAL: "listbox"
        };
        var arg$1 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$1, param, param$1);
        };
        return TestUtils.toBeVisible(expect(Curry._2(arg$1, undefined, component$1)));
      }));

Jest.test("show listbox when pressing arrow up", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        var partial_arg = {
          NAME: "Str",
          VAL: "button"
        };
        var arg = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg, param, param$1);
        };
        Curry._1(TestUtils.FireEvent.pressUp, Curry._2(arg, undefined, component$1));
        var partial_arg$1 = {
          NAME: "Str",
          VAL: "listbox"
        };
        var arg$1 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$1, param, param$1);
        };
        return TestUtils.toBeVisible(expect(Curry._2(arg$1, undefined, component$1)));
      }));

Jest.test("allow multiple selection when multiSelect is true", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(true, undefined));
        var arg = TestUtils.FireEvent.click;
        var partial_arg = {
          NAME: "Str",
          VAL: "button"
        };
        var arg$1 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg, param, param$1);
        };
        Curry._2(arg, undefined, Curry._2(arg$1, undefined, component$1));
        var partial_arg$1 = {
          NAME: "Str",
          VAL: "button"
        };
        var arg$2 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$1, param, param$1);
        };
        Curry._1(TestUtils.FireEvent.pressDown, Curry._2(arg$2, undefined, component$1));
        var partial_arg$2 = {
          NAME: "Str",
          VAL: "button"
        };
        var arg$3 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$2, param, param$1);
        };
        Curry._1(TestUtils.FireEvent.pressSpace, Curry._2(arg$3, undefined, component$1));
        var arg$4 = TestUtils.FireEvent.click;
        var partial_arg$3 = {
          NAME: "Str",
          VAL: "button"
        };
        var arg$5 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$3, param, param$1);
        };
        Curry._2(arg$4, undefined, Curry._2(arg$5, undefined, component$1));
        var partial_arg$4 = {
          NAME: "Str",
          VAL: "button"
        };
        var arg$6 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$4, param, param$1);
        };
        Curry._1(TestUtils.FireEvent.pressDown, Curry._2(arg$6, undefined, component$1));
        var partial_arg$5 = {
          NAME: "Str",
          VAL: "button"
        };
        var arg$7 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$5, param, param$1);
        };
        Curry._1(TestUtils.FireEvent.pressSpace, Curry._2(arg$7, undefined, component$1));
        return TestUtils.toBeInTheDocument(expect(ReactTestingLibrary.getByRole({
                            NAME: "Str",
                            VAL: "button"
                          }, {
                            name: "Red, Green"
                          }, component$1)));
      }));

Jest.test("hide listbox when focusing out from listbox", (function (param) {
        var screen = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        var partial_arg = {
          NAME: "Str",
          VAL: "button"
        };
        var arg = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg, param, param$1);
        };
        Curry._1(TestUtils.FireEvent.pressDown, Curry._2(arg, undefined, screen));
        var partial_arg$1 = {
          NAME: "Str",
          VAL: "listbox"
        };
        var arg$1 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$1, param, param$1);
        };
        TestUtils.assertAndContinue(TestUtils.toBeVisible(expect(Curry._2(arg$1, undefined, screen))));
        var arg$2 = TestUtils.FireEvent.blur;
        var partial_arg$2 = {
          NAME: "Str",
          VAL: "listbox"
        };
        var arg$3 = function (param, param$1) {
          return ReactTestingLibrary.getByRole(partial_arg$2, param, param$1);
        };
        Curry._2(arg$2, undefined, Curry._2(arg$3, undefined, screen));
        return TestUtils.toBeVisible(expect(ReactTestingLibrary.getByRole({
                            NAME: "Str",
                            VAL: "listbox"
                          }, {
                            hidden: true
                          }, screen)).not);
      }));

var FireEvent = TestUtils.FireEvent;

var assertAndContinue = TestUtils.assertAndContinue;

var getListbox = TestUtils.getListbox;

var getButton = TestUtils.getButton;

var HaveClass = TestUtils.HaveClass;

var TextContent = TestUtils.TextContent;

var toBeDisabled = TestUtils.toBeDisabled;

var toBeEnabled = TestUtils.toBeEnabled;

var toBeEmpty = TestUtils.toBeEmpty;

var toBeEmptyDOMElement = TestUtils.toBeEmptyDOMElement;

var toBeInTheDocument = TestUtils.toBeInTheDocument;

var toBeInvalid = TestUtils.toBeInvalid;

var toBeRequired = TestUtils.toBeRequired;

var toBeValid = TestUtils.toBeValid;

var toBeVisible = TestUtils.toBeVisible;

var toContainElement = TestUtils.toContainElement;

var toContainHTML = TestUtils.toContainHTML;

var toHaveAttribute = TestUtils.toHaveAttribute;

var toHaveClass = TestUtils.toHaveClass;

var toHaveFocus = TestUtils.toHaveFocus;

var toHaveFormValues = TestUtils.toHaveFormValues;

var toHaveStyle = TestUtils.toHaveStyle;

var toHaveTextContent = TestUtils.toHaveTextContent;

var toHaveValue = TestUtils.toHaveValue;

var toHaveDisplayValue = TestUtils.toHaveDisplayValue;

var toBeChecked = TestUtils.toBeChecked;

var toBePartiallyChecked = TestUtils.toBePartiallyChecked;

var toHaveDescription = TestUtils.toHaveDescription;

exports.FireEvent = FireEvent;
exports.assertAndContinue = assertAndContinue;
exports.getListbox = getListbox;
exports.getButton = getButton;
exports.HaveClass = HaveClass;
exports.TextContent = TextContent;
exports.toBeDisabled = toBeDisabled;
exports.toBeEnabled = toBeEnabled;
exports.toBeEmpty = toBeEmpty;
exports.toBeEmptyDOMElement = toBeEmptyDOMElement;
exports.toBeInTheDocument = toBeInTheDocument;
exports.toBeInvalid = toBeInvalid;
exports.toBeRequired = toBeRequired;
exports.toBeValid = toBeValid;
exports.toBeVisible = toBeVisible;
exports.toContainElement = toContainElement;
exports.toContainHTML = toContainHTML;
exports.toHaveAttribute = toHaveAttribute;
exports.toHaveClass = toHaveClass;
exports.toHaveFocus = toHaveFocus;
exports.toHaveFormValues = toHaveFormValues;
exports.toHaveStyle = toHaveStyle;
exports.toHaveTextContent = toHaveTextContent;
exports.toHaveValue = toHaveValue;
exports.toHaveDisplayValue = toHaveDisplayValue;
exports.toBeChecked = toBeChecked;
exports.toBePartiallyChecked = toBePartiallyChecked;
exports.toHaveDescription = toHaveDescription;
exports.DropdownListboxComponent = DropdownListboxComponent;
exports.component = component;
/*  Not a pure module */
