// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Controls_Listbox = require("./Controls_Listbox.bs.js");

function useControls(multiSelectOpt, size) {
  var multiSelect = multiSelectOpt !== undefined ? multiSelectOpt : false;
  var match = Controls_Listbox.useControls(multiSelect, size);
  var selectIndex = match.selectIndex;
  var match$1 = React.useState(function () {
        return false;
      });
  var setMenuVisible = match$1[1];
  var showMenu = function (param) {
    return Curry._1(setMenuVisible, (function (param) {
                  return true;
                }));
  };
  var hideMenu = function (param) {
    return Curry._1(setMenuVisible, (function (param) {
                  return false;
                }));
  };
  var selectIndex$1 = function (index) {
    Curry._1(selectIndex, index);
    return Curry._1(setMenuVisible, (function (param) {
                  return false;
                }));
  };
  return {
          hideMenu: hideMenu,
          highlightedIndex: match.highlightedIndex,
          highlightFirst: match.highlightFirst,
          highlightIndex: match.highlightIndex,
          highlightLast: match.highlightLast,
          highlightNext: match.highlightNext,
          highlightPrev: match.highlightPrev,
          menuVisible: match$1[0],
          resetHighlighted: match.resetHighlighted,
          selectedIndex: match.selectedIndex,
          selectedIndexes: match.selectedIndexes,
          selectHighlighted: match.selectHighlighted,
          selectIndex: selectIndex$1,
          selectNext: match.selectNext,
          selectPrev: match.selectPrev,
          showMenu: showMenu
        };
}

exports.useControls = useControls;
/* react Not a pure module */
