// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function onKeyDown(menuVisible, hideMenu, highlightFirst, highlightLast, highlightNext, highlightPrev, selectHighlighted, showMenu, $$event) {
  $$event.preventDefault();
  var key = $$event.key;
  switch (key) {
    case "ArrowDown" :
        if (menuVisible) {
          return Curry._1(highlightNext, undefined);
        } else {
          return Curry._1(showMenu, undefined);
        }
    case "ArrowUp" :
        if (menuVisible) {
          return Curry._1(highlightPrev, undefined);
        } else {
          return Curry._1(showMenu, undefined);
        }
    case "End" :
        if (menuVisible) {
          return Curry._1(highlightLast, undefined);
        } else {
          return ;
        }
    case " " :
    case "Enter" :
        if (menuVisible) {
          Curry._1(selectHighlighted, undefined);
          return Curry._1(hideMenu, undefined);
        } else {
          return Curry._1(showMenu, undefined);
        }
    case "Escape" :
        if (menuVisible) {
          return Curry._1(hideMenu, undefined);
        } else {
          return ;
        }
    case "Home" :
        if (menuVisible) {
          return Curry._1(highlightFirst, undefined);
        } else {
          return ;
        }
    default:
      return ;
  }
}

function onClick(index, selectIndex, _event) {
  return Curry._1(selectIndex, index);
}

exports.onKeyDown = onKeyDown;
exports.onClick = onClick;
/* No side effect */
