// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Listboxkit__Listbox = require("./Listboxkit__Listbox.bs.js");

function Listboxkit__ListboxComponent(Props) {
  var className = Props.className;
  var optionClassName = Props.optionClassName;
  var activeClassName = Props.activeClassName;
  var multiSelectOpt = Props.multiSelect;
  var options = Props.options;
  var multiSelect = multiSelectOpt !== undefined ? multiSelectOpt : false;
  var match = Listboxkit__Listbox.useListbox(options, multiSelect, undefined);
  var getOptionProps = match.getOptionProps;
  var highlightedIndex = match.highlightedIndex;
  var match$1 = Curry._1(match.getContainerProps, undefined);
  var onKeyDown = match$1.onKeyDown;
  var listOption = function (option, index) {
    var match = Curry._1(getOptionProps, index);
    var highlighted = highlightedIndex === index;
    var className = [
        optionClassName,
        highlighted ? activeClassName : undefined
      ].join(" ");
    return React.createElement("li", {
                key: option,
                "aria-selected": match["aria-selected"],
                className: className,
                role: match.role,
                onKeyDown: onKeyDown,
                onClick: match.onClick
              }, option);
  };
  return React.createElement("ul", {
              className: className,
              role: match$1.role,
              tabIndex: match$1.tabIndex,
              onKeyDown: onKeyDown,
              onFocus: match$1.onFocus,
              onBlur: match$1.onBlur
            }, options.map(listOption));
}

var make = Listboxkit__ListboxComponent;

exports.make = make;
/* react Not a pure module */
