// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var DropdownListbox = require("./DropdownListbox.bs.js");

var useDropdownListbox = DropdownListbox.useDropdownListbox;

exports.useDropdownListbox = useDropdownListbox;
/* DropdownListbox Not a pure module */
