// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var EventHandlers = require("./EventHandlers.bs.js");
var Controls_Listbox = require("./Controls/Controls_Listbox.bs.js");

function noop(param) {
  
}

function useFirstRender(param) {
  var isFirst = React.useRef(true);
  if (isFirst.current) {
    isFirst.current = false;
    return true;
  } else {
    return isFirst.current;
  }
}

function useUpdateEffect1(effect, deps) {
  var isFirstRender = useFirstRender(undefined);
  React.useEffect((function () {
          if (isFirstRender) {
            
          } else {
            Curry._1(effect, undefined);
          }
          
        }), deps);
  
}

function useListbox(options, multiSelectOpt, onChange, param) {
  var multiSelect = multiSelectOpt !== undefined ? multiSelectOpt : false;
  var size = options.length;
  var match = Controls_Listbox.useControls(multiSelect, size);
  var selectPrev = match.selectPrev;
  var selectNext = match.selectNext;
  var selectIndex = match.selectIndex;
  var selectHighlighted = match.selectHighlighted;
  var selectedIndexes = match.selectedIndexes;
  var resetHighlighted = match.resetHighlighted;
  var highlightPrev = match.highlightPrev;
  var highlightNext = match.highlightNext;
  var highlightLast = match.highlightLast;
  var highlightIndex = match.highlightIndex;
  var highlightFirst = match.highlightFirst;
  useUpdateEffect1((function (param) {
          if (onChange !== undefined) {
            return Curry._1(onChange, selectedIndexes);
          }
          
        }), [selectedIndexes]);
  var getOptionProps = function (index) {
    return {
            "aria-selected": Belt_Array.some(selectedIndexes, (function (i) {
                    return i === index;
                  })),
            role: "option",
            onClick: (function (param) {
                return EventHandlers.onClick(index, selectIndex, param);
              })
          };
  };
  var getContainerProps = function (param) {
    return {
            role: "listbox",
            tabIndex: 0,
            onBlur: (function (eta) {
                var param;
                var param$1;
                return EventHandlers.onBlur(resetHighlighted, param, param$1, eta);
              }),
            onKeyDown: (function (eta) {
                var param;
                return EventHandlers.onKeyDown(noop, highlightFirst, highlightLast, highlightNext, highlightPrev, true, selectHighlighted, selectNext, selectPrev, noop, param, eta);
              }),
            onFocus: (function (param) {
                return EventHandlers.onFocus(selectedIndexes, highlightIndex, param);
              })
          };
  };
  return {
          highlightedIndex: match.highlightedIndex,
          selectedIndex: match.selectedIndex,
          selectedIndexes: selectedIndexes,
          getContainerProps: getContainerProps,
          getOptionProps: getOptionProps
        };
}

exports.noop = noop;
exports.useFirstRender = useFirstRender;
exports.useUpdateEffect1 = useUpdateEffect1;
exports.useListbox = useListbox;
/* react Not a pure module */
