// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var ariaSelected = Caml_obj.caml_equal;

function onClick(index, selectIndex, _event) {
  return Curry._1(selectIndex, index);
}

exports.ariaSelected = ariaSelected;
exports.onClick = onClick;
/* No side effect */
