// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function onKeyDown(hideMenu, showMenu, menuOpen, highlightNext, highlightPrev, highlightFirst, highlightLast, selectHighlighted, $$event) {
  $$event.preventDefault();
  var key = $$event.key;
  switch (key) {
    case "ArrowDown" :
        if (menuOpen) {
          return Curry._1(highlightNext, undefined);
        } else {
          return Curry._1(showMenu, undefined);
        }
    case "ArrowUp" :
        if (menuOpen) {
          return Curry._1(highlightPrev, undefined);
        } else {
          return Curry._1(showMenu, undefined);
        }
    case "End" :
        if (menuOpen) {
          return Curry._1(highlightLast, undefined);
        } else {
          return ;
        }
    case " " :
    case "Enter" :
        if (menuOpen) {
          Curry._1(selectHighlighted, undefined);
          return Curry._1(hideMenu, undefined);
        } else {
          return Curry._1(showMenu, undefined);
        }
    case "Escape" :
        if (menuOpen) {
          return Curry._1(hideMenu, undefined);
        } else {
          return ;
        }
    case "Home" :
        if (menuOpen) {
          return Curry._1(highlightFirst, undefined);
        } else {
          return ;
        }
    default:
      return ;
  }
}

function onClick(showMenu, $$event) {
  $$event.preventDefault();
  return Curry._1(showMenu, undefined);
}

function onBlur(hideMenu, $$event) {
  $$event.preventDefault();
  return Curry._1(hideMenu, undefined);
}

exports.onKeyDown = onKeyDown;
exports.onClick = onClick;
exports.onBlur = onBlur;
/* No side effect */
